document.querySelector("nav").innerHTML='<a href="/"><img src="/Logos/CBwhite.png" alt="Creative Beast Logo"><h1>Creative Beast</h1></a><aside id="navbox"><a href="/CB-Studios/" class="navlink">CB Studio</a><a href="/All-Events/" class="navlink">All Events</a><a rel="noopener" href="https://cbeastevents.blogspot.com/" class="navlink" target="_blank">Blog</a><a href="/About-Us/" class="navlink">About Us</a><a id="homelink" href="/" class="navlink">Home</a></aside><button onclick="toggleNav()" aria-label="Expand NavBar"><span></span><span></span><span></span></button>';
document.querySelector("footer").innerHTML='<div><img src="/Logos/CBblue.png" alt="Creative Beast Logo"></div><h1>Creative Beast</h1><blockquote>- Turning Small Ideas Into BIG -</blockquote><hr/><section><article>Creative Beast event management services is one of the startup which grew from being a leading student organization in Lovely Professional University 🎓 where we bring brilliant and innovative minds together to stand, build and create. We organized various cultural events in LPU, be it a University level, national level or an International level. We have handled more than dozen of celebrities with our ways of organising an event.  We have set standards for the works we have done in the campus. We believe that the team work is something which gives the organization a name and fame for the events that are organised and just to let you know, we put our heart out for accomplishing any event.</article><div class="followLinks"> <h2>Follow Us On</h2> <div> <a href="https://m.facebook.com/CreativeBeastLPU/"><i class="fa fa-facebook-square" aria-hidden="true" style="color: #0625dd;"></i></a> <a href="https://instagram.com/creativebeastofficial?igshid=b4iuds3cauic"><i class="fa fa-instagram" aria-hidden="true" style="color: #CF075E;"></i></a> <a href="https://www.youtube.com/channel/UCiHXv7Lruf9vXLBteBP3QOA"><i class="fa fa-youtube-play" aria-hidden="true" style="color: #ff0000;"></i></a> <a href="https://www.linkedin.com/in/creative-beast-705725192"><i class="fa fa-linkedin-square" aria-hidden="true" style="color: #0077B5;"></i></a><a href="https://twitter.com/CreativebeastE1?s=09"><i class="fa fa-twitter-square" aria-hidden="true" style="color: #2CAAE1;"></i></a> </div></div></section><h2>Contact Us</h2><p>thecreativebeastlpu@gmail.com<span></span>+91 (IND) 8360274102, 8847578551</p><p class="copyright">    © Copyright 2020 creativebeastevents.com ( Creative Beast EMS Pvt. Ltd. - Events management services ) - All Rights Reserved</p><button id="BtnToTop" class="iconholder" onclick="topFunction()" aria-label="Button to navigate to top of page"><i class="fa fa-arrow-up" aria-hidden="true"></i></button>';
BtnToTop = document.getElementById("BtnToTop");
window.onscroll = function() { scrollFunction()};

function scrollFunction() {
  if ((document.body.scrollTop > 700 || document.documentElement.scrollTop > 700) && window.innerWidth>500 ) {
    BtnToTop.style.display = "flex";
  } else {
    BtnToTop.style.display = "none";
  }
}
function topFunction() {
  document.body.scrollTop = 0; // For Safari
  document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}

document.getElementById("eventNav").innerHTML='<h1>Services we deal in ...</h1><section><div class="pemplate" style="background: url(/Pemplates/concert.jpg); background-size: cover;"><a href="/Event-Category/concert.html">Music Concert</a></div><div class="pemplate" style="background: url(/Pemplates/college.jpg); background-size: cover;"><a href="/Event-Category/college-event.html">College Event</a></div><div class="pemplate" style="background: url(/Pemplates/modelling.jpg); background-size: cover;"><a href="/Event-Category/modelling.html">Modelling Show</a></div><div class="pemplate" style="background: url(/Pemplates/birthday.jpg); background-size: cover;"><a href="/Event-Category/birthday.html">Birthday Celebration</a></div><div class="pemplate" style="background: url(/Pemplates/wedding.jpg); background-size: cover;"><a href="/Event-Category/wedding.html">Wedding Organiser</a></div><div class="pemplate" style="background: url(/Pemplates/anniversary.jpg); background-size: cover;"><a href="/Event-Category/anniversary.html">Anniversary Celebration</a></div><div class="pemplate" style="background: url(/Pemplates/cultural.jpg); background-size: cover;"><a href="/Event-Category/cultural-event.html">Cultural Event</a></div><div class="pemplate" style="background: url(/Pemplates/celeb.jpg); background-size: cover;"><a href="/Event-Category/celebrity-management.html">Celebrity Management</a></div>  </section>';
document.getElementById("banner").innerHTML='<h1>Interested in our company to organise your Event</h1><p>There is no need to wait for the opportunity to come when you can create one.<br/>Creative Beast is always ready to assist you with fullest of our ability.</p><a href="/Plan-Your-Event/">PLAN YOUR EVENT</a>';
